import React, { useState } from 'react';
import { StockRecommendation } from '../types';
import { ShareIcon } from './Icons';

interface RecommendationCardProps {
    stock: StockRecommendation;
}

const StrategyBadge: React.FC<{ strategy: 'Oversold' | 'Overbought' }> = ({ strategy }) => {
    const isOversold = strategy === 'Oversold';
    const bgColor = isOversold ? 'bg-green-500/20' : 'bg-yellow-500/20';
    const textColor = isOversold ? 'text-green-300' : 'text-yellow-300';
    const dotColor = isOversold ? 'bg-green-400' : 'bg-yellow-400';
    
    return (
        <div className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${bgColor} ${textColor}`}>
            <svg className={`-ml-0.5 mr-1.5 h-2 w-2 ${dotColor}`} fill="currentColor" viewBox="0 0 8 8">
                <circle cx={4} cy={4} r={3} />
            </svg>
            {strategy}
        </div>
    )
};

export const RecommendationCard: React.FC<RecommendationCardProps> = ({ stock }) => {
    const [copied, setCopied] = useState(false);

    const handleShare = () => {
        const shareText = `AI Stock Idea (${stock.strategy}): ${stock.company_name} (${stock.stock_symbol}) at ₹${stock.current_price.toFixed(2)}. RSI is ${stock.rsi_value.toFixed(2)}. Reason: ${stock.recommendation_reason}. Generated by Indian Stock PNL & RSI Advisor.`;
        navigator.clipboard.writeText(shareText).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    return (
        <div className="bg-gray-800 p-6 rounded-lg border border-gray-700 hover:border-indigo-500 transition-all duration-300 transform hover:-translate-y-1 shadow-lg flex flex-col justify-between">
            <div>
                <div className="flex justify-between items-start">
                    <div>
                        <p className="text-xs font-semibold text-indigo-400 uppercase">{stock.stock_symbol}</p>
                        <h3 className="text-xl font-bold text-white mt-1">{stock.company_name}</h3>
                    </div>
                    <div className="text-right flex flex-col items-end">
                        <p className="text-lg font-semibold text-white">
                            ₹{stock.current_price.toFixed(2)}
                        </p>
                        <p className="text-sm text-cyan-400 mt-1">RSI: {stock.rsi_value.toFixed(2)}</p>
                    </div>
                </div>
                <div className="mt-3">
                    <StrategyBadge strategy={stock.strategy} />
                </div>
                <p className="text-gray-400 mt-4 text-sm">{stock.recommendation_reason}</p>
            </div>
            <div className="mt-4 pt-4 border-t border-gray-700 flex justify-end">
                <button
                    onClick={handleShare}
                    className="flex items-center space-x-2 text-sm text-gray-400 hover:text-white transition-colors"
                    aria-label="Share recommendation"
                >
                    <ShareIcon className="h-4 w-4" />
                    <span>{copied ? 'Copied!' : 'Share RSI'}</span>
                </button>
            </div>
        </div>
    );
};
