import React from 'react';
import { StockRecommendation } from '../types';
import { RecommendationCard } from './RecommendationCard';
import { Lightbulb } from 'lucide-react';

interface StockRecommendationsProps {
  recommendations: StockRecommendation[];
  isLoading: boolean;
  error: string | null;
  lossAmount: number;
}

const LoadingSpinner = () => (
    <div className="flex justify-center items-center space-x-2">
      <div className="w-4 h-4 rounded-full animate-pulse bg-indigo-400"></div>
      <div className="w-4 h-4 rounded-full animate-pulse bg-indigo-400" style={{ animationDelay: '0.2s' }}></div>
      <div className="w-4 h-4 rounded-full animate-pulse bg-indigo-400" style={{ animationDelay: '0.4s' }}></div>
      <span className="text-gray-300 ml-2">Finding opportunities...</span>
    </div>
);

export const StockRecommendations: React.FC<StockRecommendationsProps> = ({ recommendations, isLoading, error, lossAmount }) => {
  if (isLoading) {
    return (
        <div className="mt-8 p-6 bg-gray-800 rounded-xl border border-gray-700 text-center">
            <LoadingSpinner />
        </div>
    );
  }

  if (error) {
    return <div className="mt-8 p-6 bg-red-900/50 text-red-300 rounded-xl border border-red-700 text-center">{error}</div>;
  }

  if (recommendations.length === 0) {
    return null;
  }
  
  const formattedLoss = new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
  }).format(Math.abs(lossAmount));

  return (
    <div className="mt-12">
        <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-white flex items-center justify-center gap-3"><Lightbulb className="h-6 w-6 text-yellow-400" /> AI-Powered Recommendations</h2>
            <p className="text-gray-400 mt-2">
                Based on your unrealized loss of <span className="font-semibold text-red-400">{formattedLoss}</span>, here are stocks identified by RSI analysis that may present a recovery opportunity.
            </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {recommendations.map((stock) => (
                <RecommendationCard key={stock.stock_symbol} stock={stock} />
            ))}
        </div>
         <p className="text-center text-xs text-gray-500 mt-8">Disclaimer: This is not financial advice. Information is generated by an AI and may not be accurate. Always do your own research before investing.</p>
    </div>
  );
};
